# Generated by Django 3.2.23 on 2024-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_session',
                'managed': False,
            },
        ),
    ]
